Add support for managed discord server
Lucky3028/terraform-provider-discord pull request #13
Opened 2022-09-06 16:47 UTC by MOZGIII

2022-09-23 21:02 UTC, Lucky3028 commented
@MOZGIII 
Thank you for your contributions, and I'm sorry for being late!!!
Would you mind rebasing master branch b/c CI for the files has broken and the bug was fixed? (I think I can do it tomorrow.)

2022-09-23 21:07 UTC, Lucky3028 commented
(Ah..."tomorrow" is JST.)

2022-09-23 21:08 UTC, MOZGIII commented
Hey @Lucky3028! I should probably do more testing on this before this can be merged. I kind of hacked it together quickly, and I'm not sure it works well.
I'll be getting to configuring the discord server I made it for soon, so I'll give it a try again.

That said, if you feel like it's good enough - feel free to take it in.

I'll rebase in a bit.

2022-09-23 21:09 UTC, MOZGIII commented
Rebase done!

2022-09-23 21:18 UTC, Lucky3028 commented
Thank you!
I've never heard the "managed discord server", so I'll also want to test this when I'm free.

2022-09-23 21:20 UTC, Lucky3028 commented
II think I want to fix the md lint errors at the same time.

2022-09-23 21:48 UTC, MOZGIII commented
Feel free to take over this brach, I'll pull the changes if there are any when I get to it!

2022-09-26 10:13 UTC, Lucky3028 requested changes
I tried this PR, and I found needs to be changed.

2022-09-26 10:13 UTC, Lucky3028 commented on discord/resource_discord_server.go
> +		},
```suggestion
func baseServerSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
```

2022-09-26 10:13 UTC, Lucky3028 commented on discord/resource_discord_server.go
> +
```suggestion

func managedServerSchema() map[string]*schema.Schema {
	res := baseServerSchema()

	res["server_id"] = &schema.Schema{
		Type:     schema.TypeString,
		Required: true,
	}
	res["name"] = &schema.Schema{
		Type:     schema.TypeString,
		Optional: true,
	}

	return res
}

func serverSchema() map[string]*schema.Schema {
	res := baseServerSchema()

	res["server_id"] = &schema.Schema{
		Type:     schema.TypeString,
		Computed: true,
	}
	res["name"] = &schema.Schema{
		Type:     schema.TypeString,
		Required: true,
	}

	return res
}

```

2022-09-26 10:13 UTC, Lucky3028 commented on discord/resource_discord_server.go
> +		Schema: serverSchema(),
```suggestion
		Schema: managedServerSchema(),
```

2022-09-27 02:25 UTC, Lucky3028 approved these changes

2022-10-06 14:46 UTC, Lucky3028 commented
@MOZGIII Have you tried yet?

2022-10-06 15:11 UTC, MOZGIII commented
I'm about to try it in about an hour :D

2022-10-06 16:39 UTC, MOZGIII commented
Works

2022-10-07 01:47 UTC, Lucky3028 approved these changes

2022-10-07 01:48 UTC, Lucky3028 commented
Thank you and LGTM!

2022-10-07 01:48 UTC, merged