Mark guild Role position as computed
Lucky3028/terraform-provider-discord pull request #171
Opened 2024-10-24 21:51 UTC by Cyb3r-Jak3

Mark the position of a role as computed. I find it is easier to create roles with terraform and then move them into position manually.

Currently, I have to use
```hcl
    lifecycle {
        ignore_changes = [position]
    }
```
and this would alleviate that.

Shouldn't be a breaking change

2024-10-27 03:54 UTC, Lucky3028 requested changes
thx for your PR

2024-10-27 03:54 UTC, Lucky3028 commented on .goreleaser.yml
> +version: 2
Please make this change in other PR.

2024-10-27 03:59 UTC, Lucky3028 requested changes

2024-10-27 03:59 UTC, Lucky3028 commented on discord/resource_discord_role.go
> +				Description:  "Position of the role. This is reverse indexed, with `@everyone` being `0`.",
nits: Please make changes in other commit.
(Same PR is OK)

2024-10-27 03:59 UTC, Lucky3028 commented on docs/resources/role.md
> +- `position` (Number) Position of the role. This is reverse indexed, with `@everyone` being `0`.
nits: Please make changes in other commit.
(Same PR is OK)

2024-10-27 04:05 UTC, Lucky3028 reviewed
I think some people may want to set the roll position manually.
This PR is too destructive, isn’t it?

2024-10-27 14:51 UTC, Cyb3r-Jak3 commented
> I think some people may want to set the roll position manually.

You are still able to set the position of the role. By swapping to from Default to Computed, roles that have their position not set and are updated remotely won't trigger changes. If you have a value set for the position attribute, then changes will still be triggered.

https://github.com/hashicorp/terraform/issues/21278

2024-10-28 08:59 UTC, Lucky3028 commented
I see. Thanks!

2024-10-28 08:59 UTC, Lucky3028 approved these changes

2024-10-28 08:59 UTC, merged